# Generated by Django 2.2.19 on 2022-07-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220719_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='skug',
            new_name='slug',
        ),
    ]
