# Generated by Django 2.2.16 on 2022-08-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220825_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Можете добавить изображение к посту', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
