# Generated by Django 2.2.16 on 2022-08-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20220829_1713'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='already_following',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='not_self_follow',
        ),
    ]
