# Generated by Django 2.2.16 on 2022-08-30 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20220830_1239'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='not_self_follow',
        ),
    ]
